package com.vajraiot.VJ_RLY_RFMS_REST_APIs.enums;

public enum Events {
    DEVICE_DISCONNECT,
    VEHICLE_BATTERY_DISCONNECT,
    DEVICE_TAMPER,
    INTERNAL_BATTERY_LOW,
    EXTERNAL_BATTERY_LOW,
    FUEL_THEFT_ACTIVE,
    FUEL_FILL_ACTIVE
}
